#pragma once

#define MBC1_RAM_ENABLE_REGISTER_LOW       0x0000
#define MBC1_RAM_ENABLE_REGISTER_HIGH      0x1FFF
#define MBC1_ROM_BANK_NUMBER_REGISTER_LOW  0x2000
#define MBC1_ROM_BANK_NUMBER_REGISTER_HIGH 0x3FFF
#define MBC1_RAM_BANK_NUMBER_REGISTER_LOW  0x4000
#define MBC1_RAM_BANK_NUMBER_REGISTER_HIGH 0x5FFF
#define MBC1_BANKING_MODE_REGISTER_LOW     0x6000
#define MBC1_BANKING_MODE_REGISTER_HIGH    0x7FFF
