#pragma once 

#define LCD_RESOLUTION_X          166
#define LCD_RESOLUTION_Y          144 
#define LCD_RESOLUTION_SCALER     3


#define MODE_0_HORIZONTAL_BLANK_DOTS   204
#define MODE_1_VERTICAL_BLANK_DOTS     4560
#define MODE_2_OAM_SCAN_DOTS           80
#define MODE_3_DRAWING_PIXELS_DOTS     172
#define SCANLINE_DOTS                  MODE_0_HORIZONTAL_BLANK_DOTS + MODE_3_DRAWING_PIXELS_DOTS + MODE_2_OAM_SCAN_DOTS